// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';
  var setupViz, updateCircle;

  angular.module('hprgApp', []).controller('HPRGCtrl', [
    '$scope', function($scope) {
      return $scope.data = {
        'TTP': 'lonar.ddu-india.com',
        'GDI': 'roganjosh..ddu-india.com',
        'GLD': 'sitar.anim.dreamworks.com',
        'PDI': 'florida.pdi.com'
      };
    }
  ]).directive('viz', [
    function() {
      return {
        restrict: 'E',
        scope: {
          site: '='
        },
        link: function(scope, element, attrs) {
          setupViz(scope, element, attrs);
          scope.$watch('site', updateCircle, true);
          element.bind('mouseenter', function(event) {
            console.log('enter');
            return scope.svg.selectAll('rect').transition().style('fill', 'green').attr('height', 80).attr('width', 80);
          });
          return element.bind('mouseleave', function(event) {
            return scope.svg.selectAll('rect').transition().style('fill', 'steelblue').attr('height', 50).attr('width', 50);
          });
        }
      };
    }
  ]);

  setupViz = function(scope, element, attrs) {
    console.log('CREATE SVG!');
    console.log(scope, element, attrs.site);
    if (scope.svg == null) {
      scope.svg = d3.select(element[0]).append('svg').attr('width', 200).attr('height', 200);
    }
    console.log(scope.svg);
    return scope.svg.selectAll('rect').data([1, 2, 3]).enter().append('rect').attr('x', 50).attr('y', 50).attr('width', 50).attr('height', 50).style('fill', 'steelblue').transition();
  };

  updateCircle = function(oldVal, newVal, scope) {
    console.log('UPDATE CIRLCE!');
    return console.log(oldVal, newVal, scope);
  };

}).call(this);
